apiVersion: v1
kind: ConfigMap
metadata:
  name: shipping
  namespace: roboshop
  labels: # these labels are deployment labels
    app: shipping
    project: roboshop
    tier: app
data:
  CART_ENDPOINT: "cart:8080"
  DB_HOST: "roboshop-dev.c05wi488svl2.us-east-1.rds.amazonaws.com"
